name: export
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org8656d99b.crm8.dynamics.com/'
        user-name: 'KasifMd@kasifm.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

#     - name: export-solution action
#       uses: microsoft/powerplatform-actions/export-solution@v0
#       with:
#         environment-url: 'https://org8656d99b.crm8.dynamics.com/'
#         user-name: 'KasifMd@kasifm.onmicrosoft.com'
#         password-secret: ${{ secrets.password }}
#         solution-name: CloningApp2
#         solution-output-file: out/exported/CloningApp2.zip

#     - name: export-solution action
#       uses: microsoft/powerplatform-actions/export-solution@v0
#       with:
#         environment-url: 'https://org8656d99b.crm8.dynamics.com/'
#         user-name: 'KasifMd@kasifm.onmicrosoft.com'
#         password-secret: ${{ secrets.password }}
#         solution-name: CloningApp
#         solution-output-file: CloningApp.zip
#         working-directory: 'out'


    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org8656d99b.crm8.dynamics.com/'
        user-name: 'KasifMd@kasifm.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: EMPH2644
        solution-output-file: out/exported/EMPH2644.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/EMPH2644.zip
        solution-folder: out/solutions/EMPH2644
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org8656d99b.crm8.dynamics.com/'
        user-name: 'KasifMd@kasifm.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: cr4769c
        solution-output-file: out/exported/cr4769c.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/cr4769c.zip
        solution-folder: out/solutions/cr4769c
        solution-type: 'Unmanaged'
        overwrite-files: true
